apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: This service receives new orders and processes them
  tags:
    - nodejs
    - backend
    - r4
    - s1
    - p1
  annotations:
    sentry.io/project-slug: value
    github.com/project-slug: ankush0727/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io  
spec:
  type: service
  lifecycle: production
  owner: backend-team
